# Railway deployment configuration

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.env]
NODE_ENV = "production"

[[services]]
name = "web"
protocol = "http"
port = "3000"

[[services.environment]]
key = "NEXT_PUBLIC_API_URL"
sync = true
